document.writeln("        <ul class=\"layui-nav\">");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" target=\"_blank\" href=\"https://www.abxcdn.com/\">");
document.writeln("              定制CDN<span class=\"layui-badge-dot\"></span>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" onclick=\"linkjump(\'_self\',\'/docs/\',0);\">");
document.writeln("              文档<span class=\"layui-badge-dot\"></span>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" onclick=\"linkjump(\'_self\',\'./api.html\',0);\">");
document.writeln("              API");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" onclick=\"linkjump(\'_self\',\'./servers.html\',0);\">");
document.writeln("              检测");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" rel=\"nofollow\" target=\"_blank\" href=\"https://gitee.com/layui\">");
document.writeln("              Layui社区<span class=\"layui-badge-dot\"></span>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("        </ul>");