document.writeln("        <div class=\"layui-form component\">");
document.writeln("          <select lay-search lay-filter=\"component\">");
document.writeln("            <option value=\"\">搜索分类模块</option>");
document.writeln("            <option value=\"#Layui\">Layui</option>");
document.writeln("            <option value=\"#Layer\">Layer</option>");
document.writeln("            <option value=\"#LayDate\">LayDate</option>");
document.writeln("            <option value=\"#FlyTemplate\">FlyTemplate</option>");
document.writeln("            <option value=\"#Zip\">全文件下载</option>");
document.writeln("          </select>");
document.writeln("        </div>");
