document.writeln("        <ul class=\"layui-nav\">");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" target=\"_blank\" href=\"https://pro.layuicdn.com/\">");
document.writeln("              Pro<span class=\"layui-badge-dot\"></span>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" onclick=\"linkjump(\'_self\',\'./api.html\',0);\">");
document.writeln("              API");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" onclick=\"linkjump(\'_self\',\'./extend.html\',0);\">");
document.writeln("              组件");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" rel=\"nofollow\" target=\"_blank\" href=\"https://fly.layui.com/?rurl=LayuiCdn\">");
document.writeln("              Layui社区<span class=\"layui-badge-dot\"></span>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\"layui-nav-item layui-hide-xs\">");
document.writeln("            <a class=\"cursor-pointer\" rel=\"nofollow\" target=\"_blank\" href=\"https://www.layui.com/?rurl=LayuiCdn\">");
document.writeln("              Layui官网");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("");