document.writeln("    <div class=\"layui-footer footer\">");
document.writeln("      <div class=\"chc-friendship\">");
document.writeln("        友情链接：");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://www.layui.com/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          Layui");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://fly.layui.com/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          Layui社区");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://layim.layui.com/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          Layim");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://layer.layui.com/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          Layer");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://www.layui.com/laydate/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          Laydate");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://www.layui.com/admin/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          LayAdmin");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"http://cloud.hcwl520.net.cn/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          CHC云开放");
document.writeln("        </a>");
document.writeln("        <a class=\"cursor-pointer\" target=\"_blank\" href=\"https://cloud.hcwl520.com.cn/?rurl=CHC-CDN\" onmouseover=\"layer.tips(this.text,this,{tips:[1,\'#000\'],time:1000});\">");
document.writeln("          CHC云计算");
document.writeln("        </a>");
document.writeln("      </div>");
document.writeln("      <div class=\"layui-main\">");
document.writeln("        <p>");
document.writeln("          Copyright&nbsp;&copy;&nbsp;2012-2019&nbsp;");
document.writeln("          <a class=\"cursor-pointer\" onClick=\"linkjump(\'_self\',\'//cloud.hcwl520.com.cn/\');\">");
document.writeln("            cloud.hcwl520.com.cn");
document.writeln("          </a>");
document.writeln("          &nbsp;All&nbsp;Rights&nbsp;Reserved.&nbsp;锦江区未来滴网络工作室-CHC云计算官网&nbsp;版权所有");
document.writeln("        </p>");
document.writeln("      </div>");
document.writeln("    </div>");
